apiVersion: v1
kind: Pod
metadata:
  name: label
  # labels has filtration feature and some other functional uses.
  labels:
    app: nginx
    enviournment: DEV
    course: kubernetes
    duration: 6 weeks
spec:
  containers:
  - name: label
    image: nginx
