# docker run -p 80:80 nginx --> pull image from dockerfile and create container
kind: Pod
apiVersion: v1
metadata:
  name: stress
spec:
  containers:
  - image: satyanarayana5555/stress:v1
    name: nginx
    command: ["sleep","2000"]