apiVersion: v1
kind: Pod
metadata:
  name: env-secrets
spec:
  containers:
  - name: Pod-secrets
    image: nginx
    env:
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysql-creds
          key: username
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-creds
          key: password
      